### ISSUE TITLE
Weekend of 1/16 - 1/19

### ISSUE THREAD

**Issue by NuclearLemon** [DragonsAhoy/Project-Something#6]
- 6.11 Memory leak solution in the artificial intelligence (programming)
  - Designated Branch: Bugfixes/Memory-Leak
  - Memory leaks is contained to obj_ndf_soldier and obj_enemy_virus
  - Relevant code found in Step and Alarm 1 Events.
 - 6.12 ~~Fix non-firing ranged AI (programming)~~
  - obj_ndf_soldier fires once and quits. this is likely due to line of fire collision checking and rate of fire cooldown.
 - 6.13 Add ranged enemy AI (programming/art)
 - 6.14 Working campaign map (programming/art)
 - 6.15 Test mobo sitemap (room design)
  - Designated Branch: Features/Content/Test-Maps
  - Reference the outline and planning folder.
 - 6.16 Test HDD sitemap (room design)
  - Designated Branch: Features/Content/Test-Maps
  - Reference the outline and planning folder.
 - 6.17 Test Switch sitemap (room design)
  - Designated Branch: Features/Content/Test-Maps
  - Reference the outline and planning folder.
 - 6.18 Clickable main menu (programming)
 - 6.19 Turret/Defense placement (programming/art)
  - AI for the MG turret
  - Code for the ability to place and remove MG turrets
  - This code can then be used for future placeable defenses
 - 6.2 Map props (art)
 - 6.21 ~~Weapon proficiencies (programming)~~
  - Designated Branch: Features/Weapon-Proficiencies
  - Global Weapon proficiency attained by killing an enemy with a specific weapon
  - Higher weapon proficiency reduces weapons spread on obj_player
  - relevant code found in obj_player_step event "trajectoryoffset = random_range(-10,10);"
 - 6.22 Level scaling (programming)

Added 19:53 EST:

 - 6.23 Damage given to enemies indicator (programming)
 - 6.24 Experience received indicator (programming)

Added 20:07 EST:

 - 6.25 ~~Nerf the shotgun (programming)~~
  - The shotgun does all the damage in the world, it needs to be reduced
  - Relevant code: obj_player Step event

Added 1/18/15 00:22 EST:

 - 6.26 Foundations of a resource system
  - Farm and spend "packets (?)
 - 6.27 NDF Tank AI
  - Sprite is done (spr_ndf_tank)
 - 6.28 Miniboss AI
  - He is ranged and melee
  - Sprite is done spr_enemy_miniboss
 - 6.29 Improved NDF_Soldier AI
  - Check if friendlies close or in line of fire and move away from them

**Comment by andrew2060** [comment]
#6.2 Fixed in https://github.com/DragonsAhoy/Project-Something/pull/7

**Comment by NuclearLemon** [comment]
6.21 and 6.25 completed
